### ISSUE TITLE
[BUG] OpenMP doesn't allow unsigned integral types in for loops

### ISSUE THREAD

**Issue by jsoulier** [SimulationEverywhere/cadmium_v2#28]
**Describe the bug**

In the OpenMP standard, signed integral types must be used in for loops.
https://stackoverflow.com/questions/2820621/why-arent-unsigned-openmp-index-variables-allowed

**To Reproduce**

1. Execute build.sh on Windows with MSVC (change "make" to "cmake --build .")

**Expected behavior**

A build without any failures

**Screenshots**

```bash
C:\Users\jaans\sysc_4907\cadmium_v2_fork\include\cadmium\core\simulation\parallel_root_coordinator.hpp(85,33): error C3016: 'i': index variable in OpenMP 'for' statement must have signed integral type [C:\Users\jaans\sysc_4907\cadmium_v2_fork\build\parallel_main_asymm_sir 
.vcxproj]
  (compiling source file '../example/celldevs_sir/parallel_main_asymm_sir.cpp')
  ```

**Desktop (please complete the following information):**

Windows 11 using MSVC (Visual Studio compiler)

**Additional context**

Doesn't seem to be on issue on GCC where they have support for a newer OpenMP. MSVC is still stuck using an older one that's more restrictive.
https://stackoverflow.com/questions/2820621/why-arent-unsigned-openmp-index-variables-allowed

**Comment by romancardenas** [comment]
Sure! Shouldn't be an issue

**Comment by jsoulier** [comment]
thanks. following up with PR.
